---
title: "Activity 8"
author: "Adith Gopal and Nithika Radhakrishnan"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document:
    df_print: paged
  html_notebook: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(rvest)
library(dplyr)
library(readr)
library(ggplot2)
library(tidyr)

phi_roster <- read_html(
  x = "https://www.baseballamerica.com/teams/1024/philadelphia-phillies/roster/"
) %>%
  html_elements(css = "table") %>%
  html_table()
```

```{r}
phi_stats <- read_html(
  x = "https://www.baseball-reference.com/teams/PHI/2022.shtml"
) %>%
  html_elements(css = "table") %>%
  html_table()
```

```{r}
phi_stats <- bind_cols(phi_stats[[1]])
phi_roster <- bind_cols(phi_roster[[1]])
colnames(phi_roster)[4] <- "Batting side"
colnames(phi_roster)[5] <- "Throwing Hand"
```

```{r}
phi_stats[phi_stats == "Bryson Stott*"] <- "Bryson Stott"
phi_stats[phi_stats == "Kyle Schwarber*"] <- "Kyle Schwarber"
phi_stats[phi_stats == "Bryce Harper*"] <- "Bryce Harper"
phi_stats[phi_stats == "Brandon Marsh*"] <- "Brandon Marsh"
phi_stats <- filter(phi_stats, 
                    Pos == "C" | Pos == "1B" | Pos == "2B"|
                    Pos == "3B" | Pos == "SS" | Pos == "LF" |
                    Pos == "CF" | Pos == "RF" | Pos == "DH")
phi_stats <- phi_stats %>%
  mutate(
    HR = parse_number(HR),
    BB = parse_number(BB)
  )
```

```{r}
phi_batting <- inner_join(
  x = phi_stats,
  y = phi_roster,
  by = c("Name" = "X2")
)
```


```{r}
ggplot(phi_batting) +
  aes(x = BB, y = HR, colour = `Batting side`) +
  geom_point(shape = "circle", size = 3L) +
  scale_color_hue(direction = 1) +
  labs(
    x = "Home Runs (HRs)",
    y = "Walks Taken (BB)",
    title = "Home Runs hit vs Walks Taken for Phillies hitters in the 2022 regular season"
  ) +
  theme_gray() +
  theme(
    plot.title = element_text(size = 13L,
    face = "bold",
    hjust = 0.5),
    axis.title.y = element_text(size = 13L),
    axis.title.x = element_text(size = 13L)
  )
```

```{r}
devtools::install_github(
  repo = "claudiozandonella/trackdown",
  build_vignettes = TRUE
)

trackdown::upload_file(
  file = "Activity9.Rmd", 
  hide_code = TRUE,
  rich_text = TRUE,
  )
```

```{r}
trackdown::download_file(
  file = "Activity9.Rmd")
```

```{r}
trackdown::update_file(
  file = "Activity9.Rmd",
  hide_code = FALSE,
  rich_text = TRUE
)
```